name: Github Pages

on:
  push:
    branches: [ master ]

jobs:
  generate-push-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Do not run on release commits
    if: "!contains(github.event.head_commit.message, 'chore(release):')"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Install extras
        run: poetry install  --extras "spark glue bigquery"

      - name: Build docs page
        run: |
          poetry run pdoc --html hela
          mkdir docs
          cp -r html/hela/* docs
          rm -rf html

      - name: Deploy docs page
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: docs