name: Publish Package

on: [workflow_dispatch]

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest
    concurrency: semantic-versioning
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTICRELEASETOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Semantic Release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          poetry run semantic-release publish
        env:
          github_token: ${{ secrets.SEMANTICRELEASETOKEN }}